server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/mhazutcodes
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

